{% set name = "fairseq2" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/facebookresearch/fairseq2
  git_rev: v0.2.0

build:
  skip: True  # [py<38]
  # win officially not supported by upstream as per
  # https://github.com/facebookresearch/fairseq2/blob/v0.2.0/README.md#installing-on-windows
  skip: True  # [win]
  number: 0

requirements:
  build:
    - git  # [not win]

outputs:
  - name: fairseq2n
    build:
      script: python -m pip install ./fairseq2n/python -v --no-deps --no-build-isolation
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
      host:
        - python
        - pip
        - wheel
        - setuptools >=67.8
      run:
        - python
        - tbb >=2021.8  # [(linux or osx) and x86_64]
        # the version must be the same between extension module and fairseq2 (main module)
        # as per [this comment](https://github.com/facebookresearch/fairseq2/blob/76015a1280d72ef1f94535637579907da929297c/fairseq2n/python/setup.py#L171)
        # the same version as the subpackage fairseq2n should be pinned
        - pytorch >=1.12.1

      test:
        imports:
          - fairseq2n
        commands:
          - pip check
        requires:
          - pip

  - name: {{ name }}
    build:
      script: python -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python
        - pip
        - wheel
        - setuptools >=67.8
      run:
        - python
        - jiwer >=3.0
        - numpy >=1.23
        - overrides >=7.3
        - packaging >=23.1
        - pyyaml >=6.0
        - sacrebleu >=2.3
        - torcheval >=0.0.6
        - tqdm >=4.62
        - typing_extensions >=4.3  # [py<310]
        - {{ pin_subpackage('fairseq2n', exact=True) }}

      test:
        imports:
          - fairseq2
        commands:
          - pip check
        requires:
          - pip

about:
  home: https://github.com/facebookresearch/fairseq2
  summary: |
    fairseq2 is a sequence modeling toolkit that allows researchers and developers to train custom models for
    translation, summarization, language modeling, and other content generation tasks. It is also the successor of fairseq.
  description: |
    fairseq2 is a sequence modeling toolkit that allows researchers and developers to train custom models for
    translation, summarization, language modeling, and other content generation tasks. It is also the successor of fairseq.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://facebookresearch.github.io/fairseq2/stable
  doc_url: https://github.com/facebookresearch/fairseq2

extra:
  recipe-maintainers:
    - boldorider4
