{% set name = "fairseq2" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/facebookresearch/fairseq2
  git_rev: v0.2.0
  patches:
    - 0001-use-host-env-python.patch
    - 0002-fix-unsupported-linker-option.patch
    - 0003-unvendor-fmt.patch
    - 0004-unvendor-sentencepiece-and-zip.patch

build:
  # skip py312 because it's supported only from 0.2.1
  skip: True  # [py<38 or py>311]
  # win officially not supported by upstream as per
  # https://github.com/facebookresearch/fairseq2/blob/v0.2.0/README.md#installing-on-windows
  skip: True  # [win]
  missing_dso_whitelist:
    - $RPATH/libtorch_cpu.so     # [linux]
    - $RPATH/libtorch_python.so  # [linux]
    - $RPATH/libc10.so           # [linux]
    - $RPATH/libtorch_cpu.dylib     # [osx]
    - $RPATH/libtorch_python.dylib  # [osx]
    - $RPATH/libc10.dylib           # [osx]
    - "**/libsndfile.*.dylib"       # [osx]
  ignore_run_exports:
    - libsndfile
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
    - patch  # [not win]
    - m2-patch # [win]
    - git  # [not win]
  host:
    - python
    - pip
    - wheel
    - setuptools >=67.8
    - tbb-devel >=2021.8  # [(linux or osx) and x86_64]
    - packaging >=23.1
    - pytorch 2.3.0
    - libsndfile
    - pybind11
    # unvendored host dependencies
    - fmt 9.1.0
    - libsentencepiece 0.2.0
    - libprotobuf 4.25.3
  run:
    - python
    - jiwer >=3.0
    - numpy >=1.23
    - overrides >=7.3
    - packaging >=23.1
    - pyyaml >=6.0
    - sacrebleu >=2.3
    - pytorch >=1.12.1
    - torcheval >=0.0.6
    - tqdm >=4.62
    - typing_extensions >=4.3  # [py<310]
    - libiconv  # [osx]

  test:
    imports:
      - fairseq2
    commands:
      - pip check
    requires:
      - pip

about:
  home: https://github.com/facebookresearch/fairseq2
  summary: |
    fairseq2 is a sequence modeling toolkit that allows researchers and developers to train custom models for
    translation, summarization, language modeling, and other content generation tasks. It is also the successor of fairseq.
  description: |
    fairseq2 is a sequence modeling toolkit that allows researchers and developers to train custom models for
    translation, summarization, language modeling, and other content generation tasks. It is also the successor of fairseq.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://facebookresearch.github.io/fairseq2/stable
  doc_url: https://github.com/facebookresearch/fairseq2

extra:
  recipe-maintainers:
    - boldorider4
